name: router_example
description: Router Example
version: 0.0.1

environment:
  sdk: '>=2.0.0 <3.0.0'

# #docregion dependencies, dependencies-wo-forms
dependencies:
  angular: ^5.0.0
  # #enddocregion dependencies-wo-forms
  angular_forms: ^2.0.0
  # #docregion dependencies-wo-forms
  angular_router: ^2.0.0-alpha+19
# #enddocregion dependencies, dependencies-wo-forms

dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
